Fix for setting multiline outputs
Current way doesn't provide a proper handling.
Creates errors like:
```
Error: Unable to process file command 'output' successfully.
Error: Invalid format 'M	README.md'
```

According to https://github.com/orgs/community/discussions/24952 this should fix the issue.